Set bidders list as default explore page
KappaSigmaMu/kappasigmamu.github.io pull request #106
Opened 2022-06-15 18:59 UTC by edrd-f

Also inject `api` object like done for other pages.

2022-06-15 19:00 UTC, edrd-f commented
![](https://github.trello.services/images/mini-trello-icon.png) [When loading, show loading message/animation instead of "no entries" message](https://trello.com/c/xBO5KH6J/317-when-loading-show-loading-message-animation-instead-of-no-entries-message)

2022-06-15 19:00 UTC, edrd-f commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make bidders list the default explore page](https://trello.com/c/gS4NrHg9/315-make-bidders-list-the-default-explore-page)

2022-06-17 19:22 UTC, laurogripa requested changes
Waiting conflict resolution

2022-06-18 19:52 UTC, laurogripa approved these changes

2022-06-18 19:52 UTC, merged