WIP: Members page
KappaSigmaMu/kappasigmamu.github.io pull request #61
Opened 2021-11-17 21:17 UTC by alfakini

Merge after: https://github.com/KappaSigmaMu/kappasigmamu.github.io/pull/60

<img width="1482" alt="Screen Shot 2021-11-17 at 18 16 46" src="https://user-images.githubusercontent.com/4171/142283745-16dbf88d-98f8-4a0a-8238-986993c77ad0.png">

2021-11-17 21:51 UTC, alfakini commented
![](https://github.trello.services/images/mini-trello-icon.png) [[PAGE] Implement the Members Lists page](https://trello.com/c/Yi1OTiTx/232-page-implement-the-members-lists-page)

2021-11-25 23:20 UTC, laurogripa requested changes

2021-11-25 23:20 UTC, laurogripa commented on src/pages/explore/MembersPage/components/PayoutsAccordion.tsx
> +)
We won't show payouts on the members list, nor strikea

2021-11-25 23:20 UTC, laurogripa commented on src/pages/explore/MembersPage/MembersList.tsx
> +          {member.isDefenderVoter ? <Badge pill bg="primary" className="me-2">Defender</Badge> : <></>}
This is confusing as it shows a `defender` tag on members who voted on the defender. This induces the user into thinking that these members are defenders themselves. I think we can remove this.

2021-11-25 23:20 UTC, laurogripa commented on src/pages/explore/MembersPage/MembersList.tsx
> +          {member.hasStrikes ? <Badge pill bg="danger" className="me-2">{member.strikesCount} Strikes</Badge> : <></>}
We can remove the strikes. If needed, we can show it later on member profile.

2021-11-27 02:21 UTC, laurogripa approved these changes

2021-11-27 02:22 UTC, laurogripa requested changes
Last commit broke a test case

2021-11-28 23:55 UTC, danielSbastos approved these changes

2021-11-29 00:11 UTC, merged