[WIP] Implement vouch component
KappaSigmaMu/kappasigmamu.github.io pull request #73
Opened 2022-02-08 20:39 UTC by danielSbastos

2022-02-11 17:23 UTC, danielSbastos commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement the vouch component](https://trello.com/c/qH9EVdlU/283-implement-the-vouch-component)

2022-02-14 23:36 UTC, danielSbastos commented on .eslintrc.js
> +        "react/prop-types": "off"
This is not needed because typescript itself already forces the type declaration of props.

2022-03-11 20:41 UTC, laurogripa requested changes
Vouching is not working properly, `who` address is wrong and KSM values are not in the right format

2022-06-20 18:49 UTC, danielSbastos commented
This PR was moved to this one: https://github.com/KappaSigmaMu/kappasigmamu.github.io/pull/103

2022-06-20 18:49 UTC, closed without merging

2022-06-20 18:53 UTC, edrd-f commented
Implemented in https://github.com/KappaSigmaMu/kappasigmamu.github.io/pull/103