Remove localstorage account
KappaSigmaMu/kappasigmamu.github.io pull request #91
Opened 2022-05-10 23:26 UTC by danielSbastos

Hello darkness my old friend,

In this PR we finally remove the handling of the activeAccount and accounts from localstorage, delegating it to the keyring and extension.

2022-05-10 23:28 UTC, edrd-f commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove account from Local Storage](https://trello.com/c/pGMQntI2/298-remove-account-from-local-storage)

2022-05-10 23:42 UTC, edrd-f approved these changes

2022-05-11 23:36 UTC, laurogripa requested changes
Let's remove `accounts` but keep `activeAccount` on localStorage

2022-05-12 22:49 UTC, edrd-f approved these changes

2022-05-16 21:44 UTC, laurogripa approved these changes

2022-05-16 21:44 UTC, merged